# site settings
title: Безличный блог
subtitle: читать не обязательно
email: belozerovau@gmail.com
description: Я дал себе обещание научиться писать,<br />и теперь пишу всякую ерунду.
baseurl: "/abelozer" # the subpath of your site, e.g. /blog
url: "https://abelozer.github.io" # the base hostname & protocol for your site
author: Alexey Belozerov

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

remote_theme: andrewbanchich/forty-jekyll-theme

plugins:
  - jekyll-remote-theme

# social settings
instagram_url: https://instagram.com/belozerov
twitter_url: https://twitter.com/belozerov
facebook_url:


# build settings
markdown: kramdown

sass:
  style: compressed
